CREATE TABLE [DisplayLanguages] (
  [Id] GUID NOT NULL ON CONFLICT FAIL CONSTRAINT [UNIQUE_Id] UNIQUE ON CONFLICT FAIL, 
  [Name] VARCHAR(256) NOT NULL ON CONFLICT FAIL);


CREATE TABLE [DisplayStrings] (
  [Id] GUID NOT NULL ON CONFLICT FAIL CONSTRAINT [UNIQUE_Id] UNIQUE ON CONFLICT FAIL, 
  [LanguageId] GUID NOT NULL ON CONFLICT FAIL CONSTRAINT [FK_LanguageId] REFERENCES [DisplayLanguages]([Id]), 
  [Value] TEXT NOT NULL ON CONFLICT FAIL);


CREATE TABLE [EnchantmentCalculations] (
  [Id] GUID NOT NULL ON CONFLICT FAIL, 
  [Name] VARCHAR(64) NOT NULL ON CONFLICT FAIL COLLATE NOCASE);


CREATE TABLE [Stats] (
  [Id] GUID NOT NULL ON CONFLICT FAIL CONSTRAINT [UNIQUE_Id] UNIQUE ON CONFLICT FAIL, 
  [Name] VARCHAR(256) NOT NULL ON CONFLICT FAIL COLLATE NOCASE, 
  [DisplayStringId] GUID NOT NULL ON CONFLICT FAIL CONSTRAINT [FK_DisplayStringId] REFERENCES [DisplayStrings]([Id]) COLLATE NOCASE);


CREATE TABLE [Enchantments] (
  [Id] GUID NOT NULL ON CONFLICT FAIL, 
  [StatId] GUID NOT NULL ON CONFLICT FAIL CONSTRAINT [FK_StatId] REFERENCES [Stats]([Id]), 
  [CalculationId] GUID NOT NULL ON CONFLICT FAIL CONSTRAINT [FK_CalculationId] REFERENCES [EnchantmentCalculations]([Id]), 
  [TriggerId] GUID NOT NULL ON CONFLICT FAIL, 
  [StatusTypeId] GUID NOT NULL ON CONFLICT FAIL, 
  [SpawnLevel] INT NOT NULL ON CONFLICT FAIL, 
  [MinimumValue] FLOAT NOT NULL ON CONFLICT FAIL, 
  [MaximumValue] FLOAT NOT NULL ON CONFLICT FAIL,
  [MinimumDuration] FLOAT NOT NULL ON CONFLICT FAIL, 
  [MaximumDuration] FLOAT NOT NULL ON CONFLICT FAIL);


CREATE TABLE [EnchantmentStatuses] (
  [Id] GUID NOT NULL ON CONFLICT FAIL, 
  [Name] VARCHAR(64) NOT NULL ON CONFLICT FAIL COLLATE NOCASE);


CREATE TABLE [EnchantmentTriggers] (
  [Id] GUID NOT NULL ON CONFLICT FAIL, 
  [Name] VARCHAR(64) NOT NULL ON CONFLICT FAIL COLLATE NOCASE);


